### ISSUE TITLE
Colorpicker farbelous en 404

### ISSUE THREAD

**Issue by bugeaud** [MedShake/MedShakeEHR-base#127]
La dépendance de composer farbelous/bootstrap-colorpicker n'existe plus dans github.

La référence est faite dans https://github.com/MedShake/MedShakeEHR-base/blob/master/public_html/composer.json ligne 145

Or le résultat de https://github.com/farbelous/bootstrap-colorpicker est maintenant un HTTP 404. L'ensemble du compte de farbelous semble avoir disparu ...

Il semble y avoir un remplaçant :
https://github.com/itsjavi/bootstrap-colorpicker

Si tel est le cas, il faut modifier la référence :

`       {
          "type": "package",
          "package": {
              "name": "itsjavi/bootstrap-colorpicker",
              "version": "3.4.0",
              "source": {
                  "url": "https://github.com/itsjavi/bootstrap-colorpicker.git",
                  "type": "git",
                  "reference": "3.4.0"
              }
}
        },`

Puis changer le require plus bas en 

`"itsjavi/bootstrap-colorpicker": "3.4.0",`

Reste à vérifier la compatibilité au niveau de l'API du picker ...

**Comment by MedShake** [comment]
Merci, je vais essayer de regarder tout cela avec l'idée surtout de supprimer le besoin de dépendance. 
A priori les navigateurs devraient être plus murs qu'à l'époque pour utiliser les fonctions internes HTML 5.

B.

**Comment by MedShake** [comment]
Voilà le fix HTML 5 est poussé sur master [bebf369](https://github.com/MedShake/MedShakeEHR-base/commit/bebf3696988640e1fd82f19ae8782e53a024627d).
Merci pour ce retour !

**Comment by bugeaud** [comment]
Semble bon 👍
