### ISSUE TITLE
Executable bit set on files & class ?

### ISSUE THREAD

**Issue by bugeaud** [MedShake/MedShakeEHR-base#129]
Bonjour,

Une classe a le bit exécutable de positioné 
https://github.com/MedShake/MedShakeEHR-base/blob/master/class/msMotSuivi.php

Est-ce une erreur ou y a-t-il une raison spécifique ?

Le retour de la commande 'find . -type f -executable' dans public_html donne (thirdparty exclus car il y en a un max) :
./js/dicom.js
./js/general.js
./js/lap.js
./js/lapHistoriqueOrdos.js
./js/lapOrdonnance.js
./js/lapPrescription.js
./js/lapTTenCours.js
./js/patient.js
./js/relations.js

Et il y a aussi l'essentiel des template twig qui sont aussi en +x ... je n'ai pas trouvé dans la doc que ceci soit un prérequis ni une bonne pratique.

++

**Comment by MedShake** [comment]
Euhhh ???!
je découvre avec grande surprise que les droits des fichiers remonteraient ici ????
On voit ça comment ? 

B.

**Comment by bugeaud** [comment]
Seul le bit execute remonte dans Git/github. Un coup de nettoyage sur base et les modules serait le bienvenu. Pas vu d'usage détourné de ce bit set pour l'heure mais celà reste une bonne pratique de sécurité que de ne pas pousser de +x sans raison.

Un truc style ...
`find . -type f -executable -print | xargs git update-index --chmod=-x`
doit faire l'affaire s'il n'y a rien qui doit être +x dans le répertoire ... suivi d'un commit.

**Comment by MedShake** [comment]
Merci, c'est fait. 
Correction pour la base poussée 32bff3a3d6d92736f4d55f35fc62c00b9ac14484
Un fichier concerné aussi sur le module gynéco obs, correction poussée également.

Moins bête ce soir je serai encore à nouveau !

**Comment by bugeaud** [comment]
Merci 👍
