### ISSUE TITLE
Compatibilité IPv6 dans msLog

### ISSUE THREAD

**Issue by bugeaud** [MedShake/MedShakeEHR-base#136]
Dans le cas actuel, la classe msLog de EHR présupose pour les logs que l'IP de l'utilisateur connecté est IPv4. Or, la forme d'une IPv6 n'a pas une structure identique.

En cas de connexion d'un client par IPv6 (adresse de lien local ou publique), une exception sera levée qui provoquera l'échec d'enregistrement de la trace avec possiblement la perte du contexte IP cause.

Voir
https://github.com/MedShake/MedShakeEHR-base/blob/master/class/msLog.php#L72
`  if(!preg_match("#[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}#",$userIP)) throw new Exception("UserIP n'est pas valide");`

La méthode setUserIP ne semble utilisée que sur 
https://github.com/MedShake/MedShakeEHR-base/blob/master/controlers/logs/actions/inc-ajax-searchAccessLog.php

Une possible regexp de remplacement 
https://www.regextester.com/104038

**Comment by MedShake** [comment]
Merci, c'est fixé ici 1217c61bd2e725debd74a5b6572e8de20a7a7483
Et merci à chatGPT qui m'a retrouvé la fonction du premier coup ;-)

**Comment by bugeaud** [comment]
Google Search uberisé par un autre bot, la vie 😉
