### ISSUE TITLE
Règlement combo liste uniquement les règlements de base

### ISSUE THREAD

**Issue by bugeaud** [MedShake/MedShakeEHR-base#137]
Pour certains utilisateurs créés avec un module non base, lors de la création d'un règlement, on obtient uniquement la liste des règlements possible de base et non pas la liste des règlements possibles correspondant au module positionné.

Sur un système, j'ai un utilisateur historique gynobs qui fonctionne et liste les règlements de gynobs, mais les nouveaux utilisateurs gynobs eux n'ont qu'une liste des J'ai un utilisateur 

https://github.com/MedShake/MedShakeEHR-base/blob/master/class/msReglement.php#L259

Le template retourné provient de `templates/base/patient/patientReglementForm.html.twig ` qui semble être construité par `controlers/patient/actions/inc-ajax-extractReglementForm.php` via l'appel à `msReglement->getFacturesTypesMenus()` le code SQL correspondant étant :

```
select a.* , c.label as catLabel
        from actes as a
        left join actes_cat as c on c.id=a.cat
        where a.toID in ('0','".$this->_userID."') and c.module='".$this->_module."' and a.active='oui'
        group by a.id
        order by c.displayOrder, c.label asc, a.label asc
```

Or dans les cas problèmatiques, il semble que `$this->_module` vaut `base`

Je n'ai pas de traces particulières pouvant expliquer les comportement de l'un ou l'autre des utilisateurs.
Les utilisateurs qui marche ou non, n'ont pas de paramètres de configuration particuliers et sont tous les deux valides.

**Comment by MedShake** [comment]
Avant que j'investigue, dis-moi si cet écran est bien identique pour les 2 utilisateurs. 

![screenshot-192 168 1 5-2023 01 09-18_43_49](https://user-images.githubusercontent.com/24508646/211372936-9d25d8fd-d660-4849-a68d-8e26015a8772.png)

En effet, comme dit ailleurs, le système des règlements est très complexe dans le logiciel et pas mal de problèmes viennent de la sélection et du réglage de toutes ces options.

**Comment by bugeaud** [comment]
Bien vu, erreur de ma part. Dsl pour le dérangement.

**Comment by MedShake** [comment]
Y'a pas de problème. Il vaut mieux dans ce sens-là :-)
