### ISSUE TITLE
Generation d'appels toute les 5 sec sur simple page login

### ISSUE THREAD

**Issue by bugeaud** [MedShake/MedShakeEHR-base#140]
La simple présence sur /login/ présente un rafraichissement sur /ajax/getPatientsOfTheDay renvoyé en 302 puis un GET sur /login/ de nouveau, etc toute les 5 sec environ. Soit 24 requètes HTTP minimum tracées par minute par onglet ouvert avec /login/ a minima.

Celà génère des traces peu utile dans les logs et une charge non nécessaire ainsi qu'un stockage disque non nécessaire.

**Comment by MedShake** [comment]
Voilà, c'est fixé, merci
N'est gardé que le JS réellement utile sur la page de login.
