### ISSUE TITLE
Derniers bugs mineurs de la V8

### ISSUE THREAD

**Issue by marsante** [MedShake/MedShakeEHR-base#148]
3 bugs mineurs que j'ai pu constater en cours d'utilisation de la v8 : 
- Bug qui touche tous les modules base compris sur la V8. Quand on veut visualiser un document PDF l'aperçu renvoie vers la page de login, se loguer ne change rien, ouvrir dans un nouvel onglet permet de visualiser le document. Quand c'est un jpg l'aperçu fonctionne.
-  Bug qui touche a minima les honoraires libres pour base, chiro, osteo (pas testé les autres). Lors de l'aperçu d'un règlement Tarif et Modulation ne renvoie aucune valeur alors que facturé ce jour et chèque (ou espèce ou carte) affiche la bonne valeurs. Seul le € du template twig est affiché. J'ai regardé le template twig et dans la base de donnée sans trouver de différence à mon niveau de compréhension dans le codage des différentes valeurs. Le tarif et la modulation SS du module de base passe bien sans que j'observe non plus de différence de codage.
- Bug qui touchait dans les versions précédentes uniquement les installations en différent conteneur de docker, mais qui touche depuis la version 8 les VM également. Après une installation en cli, le premier lancement de msehr.local ne redirige plus vers msehr.local/install.php ou vers la page de première connexion. Il faut manuellement aller sur msehr.local/install.php et une fois fait, taper msehr.local redirige comme avant.

**Comment by MedShake** [comment]
Rapports individualisés.
