### ISSUE TITLE
Erreur à la consultation d'un patient

### ISSUE THREAD

**Issue by mhoungbo** [MedShake/MedShakeEHR-base#152]
Bonjour à tous

J'ai une installation v8.0.3 en test avec une base d'une centaine de patients.

![detail](https://github.com/MedShake/MedShakeEHR-base/assets/893129/f48f1f1b-4486-4bcf-81bc-8116026e8125)

Lors du cliques sur le lien "Afficher plus de résultats" dans la liste des patients ;

La page suivante de la liste des patients apparait, mais la consultation d'un patient génère une erreur "Cette page semble ne pas exister !" avec une url incorrecte. 

Au lieu de https://192.168.1.1/patient/79 mais le lien est plutôt https://192.168.1.1//79, d'où l'erreur.

![image](https://github.com/MedShake/MedShakeEHR-base/assets/893129/9ec8de6b-4e24-4e75-882b-195a04ec6bf1)

Une piste pour regler ce bug ?

Merci à vous

**Comment by MedShake** [comment]
Résolu ici : 68cc113e9dae0f164376ce2d81de187eca612b45
v8.0.4 à venir dans les minutes qui viennent

**Comment by mhoungbo** [comment]
Merci
