### ISSUE TITLE
Message d'erreur sur la 8.0.4

### ISSUE THREAD

**Issue by marsante** [MedShake/MedShakeEHR-base#153]
Je suis de retour pour les tests. Merci pour les correctifs.

Lors d'une installation fraiche de la 8.0.4 je me rends sur msehr.local, puis j'appuie sur suivant. Une erreur apparait : 

> Fatal error: Uncaught Error: Call to undefined method AltoRouter::getAllActiveRoutes() in /home/ehr/class/msTools.php:57 Stack trace: #0 /home/ehr/public_html/install.php(216): msTools::redirRoute('userLogInFirst') #1 {main} thrown in /home/ehr/class/msTools.php on line 57

Reproduit sur VM et conteneur Debian 12

**Comment by MedShake** [comment]
Aaarff ... je pense avoir fixé, mais je ne peux pas tester rapidement. Si tu peux me dire ...
Merci !

**Comment by marsante** [comment]
Ça corrige le bug. Merci
