### ISSUE TITLE
Erreur dans la mise jour des info via Identifiant RPPS

### ISSUE THREAD

**Issue by rezgui** [MedShake/MedShakeEHR-base#154]
Erreur dans la mise jour des info via Identifiant RPPS.
![image_2023-11-09_210743377](https://github.com/MedShake/MedShakeEHR-base/assets/1289096/a8b50afa-8ddd-4c0c-b93c-34a5ef776271)

**Comment by MedShake** [comment]
Bug finalement inexistant selon l'auteur de la notification initiale.
