### ISSUE TITLE
Améliorer les patrons d'impression par défaut

### ISSUE THREAD

**Issue by bugeaud** [MedShake/MedShakeEHR-base#36]
Une partie des données des patrons est écrite en dur alors que l'information pourrait être récupérée du contexte utilisateur ou métier.

Avoir des patrons prêt par défaut faciliterait la mise en place d'instances de EHR.

**Comment by MedShake** [comment]
Alors, alors ... j'ai déjà traité cette question avec @fr33z00, mais pas publiquement je crois.  
Le constat premier quand on regarde le système est place est le suivant : pourquoi ne pas extraire les informations variables du profil utilisateur et faire un simple insert dans les patrons prédéfinis ? C'est quelque chose qui semble pourtant couler de source, mais ce n'est pas la solution retenue et il y a plusieurs explications à cela. 

D'abord il est impossible d'obtenir quelque chose de propre avec un patron standard et l'insertion des variables. Entre les différents diplômes et qualification, les "ancien interne de ...", les contraintes horaires, les emails, les plages téléphoniques obtenir un résultat nickel et harmonieux, sans retour ligne foireux, relève de la sorcellerie :-)    
Ceci est déjà assez complexe si on parle d'ordonnance basique, à un seul nom de praticien, mais dans un cabinet de groupe, souvent tous les praticiens sont listés sur l'ordonnance ... Faire tout ça automatiquement serait  donc un challenge de sorcellerie niveau magie noire :D 

Il y a également un autre point à prendre en compte : celui qui imprime ne le fait pas toujours pour son propre compte. Typiquement, c'est la secrétaire qui prépare des pièces à signer plus tard par le praticien. C'est aussi le remplaçant qui travaille en éditant ses pièces au nom du remplacé.

L'idée finale pour essayer de combiner le plus simplement toutes ces contraintes est celle retenue : chaque utilisateur dispose d'un dossier avec ses propres patrons et s'il n'a pas ce paramètre activé, alors c'est le dossier par défaut qui est utilisé. Un dossier peut être propre à un utilisateur strict ou commun. Cela résout un très grand nombre de cas de figure simplement et évite la création d'un système de délégation complexe juste pour cette tâche (délégation dont on peut voir les prémices sur la table objets_data avec le champ byID).

Dans le cadre de la dockerisation, et si j'ai bien compris les choses, il me semble qu'il faille prévoir un dossier patrons sur la machine hôte qui hébergera les sous-dossiers de chacun.    

Une idée d'amélioration serait d'injecter un peu de wysiwyg dans l'édition des templates. Je ne l'ai pas essayé, car ce n'est pas une priorité évidente : on ne change pas ses modèles tous les 4 matins. 

B.

**Comment by bugeaud** [comment]
Il y a plusieurs cas : 
- Soit la donnée existe dans le modèle de donnée et il faut simplement l'injecter dans le contexte qui sera accessible par le template
- Soit la la donnée n'existe pas dans le modèle de donnée et il faut se poser la question de la pertinence de le rajouter (sous une forme structurée, ou non structurée comme du texte brut ou un morceau d'HTML) dans le modèle et ensuite de l'injecter dans le contexte
- Soit la donnée est dans le contexte ... et alors il n'y a qu'à l'utiliser dans un template par défaut. :)

Le cas de la secrétaire rentre typiquement dans ce tryptique : si le praticien ayant effectué l'acte n'est pas dans le modèle de donnée il faut l'ajouter car c'est une information importante à capter.  Si le praticien n'est pas dans le contexte injecté lors de l'appel du template, il faut le rajouter car cette info est classiquement attendu dans un rapport associé à un acte/consultation. Et enfin, si cette info est bien dans le contexte, il faut simplement y accèder dans le template par défaut. J'essayerai de creuser ce point à l'occasion ... Au passage, avez-vous le modèle de donnée de EHR de maintenu quelque part en dehors du simple DDL ? 

Au delà de la contenerisation, l'industrialisation pousserait à mon sens à fournir une sépration claire entre des template par défaut (qui sont fournies dans un répertoire de l'appli ou du module) et des instances dérivées (qui sont potentiellement des copie locales de ces template par défaut mais sont impérativement dans un répertoire utilisateur dédié). Actuellement, les choses ne sont pas aussi séparées et celà peut poser des problèmes lors des monter de versions car ce qui a été personalisé sur un environemnent n'est pas clairement isolé de l'application sortie du carton.

L'apport d'une IHM Wysiwyg ne me semble également pas une grande priorité, c'est toujours trés complexe et je pense qu'il serait sage de partir sur des briques existantes. De pluus, en tout logique, celà devrait passer aprés le remplacement de la solution de génération de PDF (impactée par l'arrêt du support des appels natifss Java dans GCC). Une nouvelle solution de génération peut venir avec son propre éditeur de template... Les solutions clientes autour de JS sont légions (s'apuyant sur le CSS3 ou  du PDF). Il peut aussi être possible de rester sur des valeurs sures type XSL-FO toujours puissantes mais évoluant peu.

++
JB

**Comment by MedShake** [comment]
Ces questions sont partiellement résolues maintenant version après version.
