### ISSUE TITLE
Création de praticien avec un nom seul

### ISSUE THREAD

**Issue by bugeaud** [MedShake/MedShakeEHR-base#37]
Si on crée un praticien (Praticien / Nouveau Praticien) avec un nom seul (Nom de naissance) alors, la création semble être effectuée (écrans suivants OK), mais toutefois le praticien ne sera pas trouvable dans la liste ou la recherche.

Si on crée le même praticien en ajoutant un prénom, la création se passe également bien mais il devient possible de le retrouver dans la liste ou la recherche.

Deux possibilités : soit mettre nom+prenom en champ obligatoire, soit corriger la création d'un praticien avec un nom seul.

**Comment by MedShake** [comment]
De retour, 
Je vais regarder ça la semaine prochaine, merci !

B.

**Comment by MedShake** [comment]
J'ai bien une required sur le prénom. Ce n'est pas une garantie absolue, mais tout navigateur moderne nécessaire à l'EHR devrait donc imposer la saisie du prénom.  

B.
