### ISSUE TITLE
Mise à jour MedshareEHR-base 3.1.0 vers 4.1.0 beta 3

### ISSUE THREAD

**Issue by sambot83** [MedShake/MedShakeEHR-base#38]
Bonjour,

je me demande si dans le fichier sqlUpgrade_v3.1.2_v4.0.0_post.php :

 Ligne 34 : ajouter ['config'] à ($p['config']['webDirectory']
Ligne 37: remplacer $agendaFiles par $rdvFiles dans le foreach

Eric

**Comment by fr33z00** [comment]
Bonjour, Eric.
Effectivement, ce sont bien là 2 coquilles. Merci de les avoir dénichées et rapportées.
