### ISSUE TITLE
Mise à jour 3.1.1 vers 4.0.0

### ISSUE THREAD

**Issue by sambot83** [MedShake/MedShakeEHR-base#39]
Bonjour,
j'essaye de mettre à jour Medshake, après la mise à jour, j'ai perdu tout le design et je ne trouve pas le fichier base.css

<link type="text/css" href="http://192.168.0.13/medshake/css/base.css" rel="stylesheet">

est-il manquant?

Merci,
Eric de R-OPS

**Comment by sambot83** [comment]
Erreur dans le navigateur:

Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://192.168.0.13/medshake/thirdparty/FortAwesome/Font-Awesome/web-fonts-with-css/css/fontawesome-all.min.css".

Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://192.168.0.13/medshake/css/base.css".

**Comment by MedShake** [comment]
Bonjour
A priori, un coup de composer update devrait mettre les ressources tiers à jour : nouvelle version de twitter et fontawesome. 
A priori cela est géré théoriquement par le fichier php d'update mais quelque chose n'a pas du fonctionner. 

B.

**Comment by sambot83** [comment]
Merci pour la réponse rapide, j'ai fait un composer update et j'ai la version: 
Composer version 1.7.2 2018-08-16 16:57:12
mais toujours le même souci

Eric

**Comment by sambot83** [comment]
Super ça marche!
il faut composer 1.7.2
Merci.
