### ISSUE TITLE
Unable to upload some file on patient record

### ISSUE THREAD

**Issue by bugeaud** [MedShake/MedShakeEHR-base#43]
When trying to upload some file on some record, the upload fail without any alert on the web UI or console, only trace at server side of this issue is :

[Wed Jan 02 10:49:26.090394 2019] [php7:warn] [pid 608] [client client-ip:39918] PHP Warning:  finfo::file(): Empty filename or path in /app/MedShakeEHR-base/class/msTools.php on line 182, referer: http://server-name/patient/828/
[Wed Jan 02 10:49:26.090435 2019] [php7:warn] [pid 608] [client client-ip:39918] PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /app/MedShakeEHR-base/controlers/patient/actions/inc-ajax-uploadNewDoc.php on line 40, referer: http://server-name/patient/828/

The upload fail as there are no such a file in the list of files attached to the record after the alleged upload.

For the patient that fail in such a way, no upload is possible at all (including images or text file).

I have been unable to find out a pattern on file name or patient name that can explain the reason. 

After a failure on a given patient, you might still create new patient and have succesfull file uploard as well. Very odd issue...

**Comment by MedShake** [comment]
Merci pour ce retour. 
Visiblement, il n'y a pas de fichier et s'il n'y a pas de fichier, il faut regarder en priorité, il me semble, quel est le fichier source, son type et sa taille. 
Une raison basique est de voir si tout colle pour niveau taille dans le php.ini :  upload_max_filesize, post_max_size ? 
De plus les tests concluants et non concluants sont ils toujours faits avec le même fichier ? 
Enfin dans le logs, dans l'admin, concernant l'écriture en bdd, en cas de raté, y'a t'il quand même des lignes créées ? Ca ne devrait pas être le cas au vu du fichier inc-ajax-uploadNewDoc.php? Cela devrait donc impacter aucunement le fonctionnement du dossier patient concerné. 
(Il est vrai d'ailleurs que ce fichier manque un peu de contrôle et de retours vers l'utilisateur.
Je note ça dans la todo list. )

B.

**Comment by bugeaud** [comment]
Les valeurs par défaut de php.ini sont :

upload_max_filesize = 2M
post_max_size = 8M

Le fichier dépasse les 2Mo, en passant le upload_max_filesize à 10M sur le php.ini global, mes premiers tests passent maintenant. Mais vu que le php.ini est global, je pense qu'il vaut mieux passer par une surcharge locale type :
https://stackoverflow.com/questions/949415/overriding-upload-max-filesize

Je vais voir pour tester ça.

**Comment by bugeaud** [comment]
Super, merci ! Je testerais ça DQP (certainement en même temps qu'une monté de version de mon instance en prod).
