### ISSUE TITLE
Où trouver faireFse.php, lireCpsEtVitale.php

### ISSUE THREAD

**Issue by vjardin** [MedShake/MedShakeEHR-base#46]
Je ne trouve pas les scripts php utilisés en référence dans msVitale.php:

https://github.com/MedShake/MedShakeEHR-base/blob/20d0e9ce7d0a60e3c46bfca7aa8a0d91398b67d1/class/msVitale.php#L40

ou bien dans 
  https://github.com/MedShake/MedShakeEHR-base/blob/20d0e9ce7d0a60e3c46bfca7aa8a0d91398b67d1/public_html/js/vitale_functions.js#L117

Quid d'un répo git ?

merci,

**Comment by MedShake** [comment]
Bonjour

Ces scripts ne sont pas publiquement disponibles. Ils sont spécifiques à VitalOnline.

Pour ce qui est des faireFse.php, il s'agit d'un bout de code qui génère un formulaire html ne contenant que des champs hidden et envoyant vers VitalOnline. En gros c'est donc ce qui sort les data nécessaires vers le système de facturation.

Pour lireCpsEtVital.php, il retourne du json avec les champs CPS et Vital. De mémoire, l'arbo correspond à la structuration des datas dans les cartes respectives. 

B.

**Comment by vjardin** [comment]
merci @MedShake 
Est-ce que la seule solution c'est VitalOnline, où est-ce qu'il existe des alternatives ?

**Comment by MedShake** [comment]
Toutes les alternatives sont possibles à partir du moment où on construit ces 2 scripts : un pour récupérer les datas CPS/Vital, l'autre pour passer les données à facturer. 
Il faut bien sûr que le service tiers propose des moyens d’interactions. 

B.

PS : il n'est pas impossible qu'il traîne des références à VitalOnline sur des portions de script de niveau supérieur aux 2 évoqués ci-dessus. Dans ce cas, on pourra réviser ça.

**Comment by vjardin** [comment]
ok, je vais grenouiller.
