### ISSUE TITLE
Problem in medshake.zip

### ISSUE THREAD

**Issue by eda007171** [MedShake/MedShakeEHR-base#52]
Hello All

Please can you support me i have a problem in the install-self.php and i cant reach the medshake.zip file.

"Fatal error: Uncaught Error: Class 'ZipArchive' not found in /var/www/html/Gyn/gyn/self-installer.php:68 Stack trace: #0 {main} thrown in /var/www/html/Gyn/gyn/self-installer.php on line 68"

Thank you for helping us.

Regards

**Comment by indelog** [comment]
Hello,

This is a late response but its may can be useful for other users who may encounter this probleme.

This error message means you haven't got php Zip module installed.

On Debian GNU/Linux you can install it by run `apt install php-zip`.
